from .discovery import COMPANY_DISCOVERY_PROMPT, COMPANY_EXTRACTION_PROMPT
from .enrichment import (
    WEBSITE_ANALYSIS_PROMPT,
    COMPANY_ENRICHMENT_PROMPT,
    DPP_FIT_SCORING_PROMPT,
    NEWS_ANALYSIS_PROMPT,
)
from .people import CONTACT_DISCOVERY_PROMPT, CONTACT_EXTRACTION_PROMPT
from .email import EMAIL_GENERATION_PROMPT
