"""
Avelero identity layer: shared context embedded in every prompt.

Provides AVELERO_CONTEXT -- a concise, information-dense summary of
who Avelero is, what DPP is, the target market, and the value prop.
Kept under ~2000 tokens to leave room for task-specific instructions.
"""

AVELERO_CONTEXT = """\
## Avelero -- Company Context

Avelero is a fashion-tech SaaS company providing a digital product passport (DPP) \
platform built for fashion, streetwear, and lifestyle brands. Founded by Rafael Mevis, \
headquartered in Europe. Website: https://www.avelero.com

### What Is a Digital Product Passport (DPP)?

A DPP is a product-level digital record containing material origins, environmental \
impact data, care instructions, and end-of-life options (repair, resale, recycling). \
Consumers access passports by scanning a QR code on the product label or packaging. \
The EU Ecodesign for Sustainable Products Regulation (ESPR) mandates DPPs for all \
textile products entering the EU market by mid-2028.

### Avelero Platform Capabilities

- Passport Designer: Fully customizable templates (typography, colors, layouts). \
Embeds care guides, repair services, resale options, brand storytelling, newsletter \
signups, and campaign banners. On-brand experience, not generic compliance pages.
- LCA Engine: ML-powered lifecycle assessment using ISO 14040/14044 methodology. \
Estimates carbon and water impact from minimal input. No environmental science \
background required.
- Data Integration: Accepts Excel, PDF, direct uploads. API connections to Shopify, \
PLM, and ERP systems. AI-powered data gap detection and auto-completion.
- GS1 Digital Link Standard: QR codes follow the GS1 Digital Link structure, avoiding \
vendor lock-in. A single QR code serves both consumer passport access and POS scanning.

### Value Proposition (Three Pillars)

1. Speed: Most brands go from raw data to live passports in days, not months.
2. Post-Purchase Engagement: Passports embed care guides, repair services, and resale \
options that keep customers returning after purchase -- a revenue and retention channel.
3. Regulatory Readiness: Built around EU ESPR compliance. Built-in LCA engine eliminates \
separate environmental assessment subscriptions.

### Target Market

Mid-market fashion, streetwear, and lifestyle brands that:
- Sell physical products (apparel, footwear, accessories) in the EU market
- Have 20-500 employees
- Face upcoming EU DPP compliance deadlines (mandatory mid-2028)
- Value speed of implementation over enterprise customization
- Care about brand experience and post-purchase customer engagement

### Competitive Differentiation

Avelero differentiates from enterprise solutions (Avery Dennison, SAP) on speed and \
cost, and from luxury-focused competitors (Arianee, EON) on mid-market accessibility \
and design customization. Key advantages:
- Days-not-months deployment vs. enterprise competitors
- Design-forward passport customization vs. generic compliance tools
- Built-in LCA engine (no separate sustainability subscription)
- GS1 Digital Link standard (interoperability, no vendor lock-in)
- Fashion-specific focus vs. cross-industry platforms

### Regulatory Timeline (Critical for Sales Messaging)

- July 2024: ESPR entered into force
- July 2026: EU centralized DPP registry becomes operational
- Late 2026 to Q2 2027: Textile delegated act adoption expected
- Mid-2028: Mandatory DPPs for all textile products in EU
- Fashion has 6-10 month pre-production lead times, so QR codes must be generated by \
Q3-Q4 2027. DPP vendor selection needs to happen in 2026.

### Outreach Identity

All outreach is sent by Moussa on behalf of Avelero. Sign-off: "Moussa, Avelero"
"""


def build_system_prompt(task_instructions: str) -> str:
    """
    Combine Avelero context with task-specific instructions.

    Args:
        task_instructions: The task-layer prompt (discovery, enrichment, etc.)

    Returns:
        A single system prompt string with context + instructions.
    """
    from src.prompts.runtime import resolve
    context = resolve("avelero_identity", AVELERO_CONTEXT)
    return f"{context}\n---\n\n{task_instructions}"
